### ISSUE TITLE
no error for over-long character literal

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/JuliaSyntax.jl#109]
I get
```
julia> 'abc'
'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)
```
Should be
```
julia> 'abc'
ERROR: syntax: character literal contains multiple characters
```

**Comment by c42f** [comment]
This is part of a broader problem with diagnostics not being present in validating `string->value` conversions. The general fix for these kind of issues is something like https://github.com/JuliaLang/JuliaSyntax.jl/issues/82#issuecomment-1232317622

**Comment by c42f** [comment]
This was somewhat improved as a side effect of #121 but still needs a more systematic fix.
