### ISSUE TITLE
`a b` in REPL treated as incomplete

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/JuliaSyntax.jl#110]
If I enter
```
julia> a b<enter>
```
it waits for more input. This should be an immediate "extra token" error.

**Comment by JeffBezanson** [comment]
Also happens for `1))`.

**Comment by KristofferC** [comment]
I tried this on 1.7, 1.8 and 1.9 and it seems to work correctly on all of them. So I am confused when this actually was a proboem.

**Comment by c42f** [comment]
That's puzzling, this reproduces easily for me if I type `a b\n`  (just a single `\n`)

@kushal140 you need `JuliaSyntax.enable_in_core!()` to enable the new parser?

**Comment by kushal140** [comment]
No , I directly ran the codes on repl.
No changes were made .

**Comment by KristofferC** [comment]
Wait, I thought I was in the julia repo and this was with the standard parser..

**Comment by c42f** [comment]
> The result shown is for standard parser.

That point is that `JuliaSyntax` is not yet the standard parser, so you need to enable it or it won't be used in the REPL.
