### ISSUE TITLE
extra newline after error output in REPL

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/JuliaSyntax.jl#111]
```
julia> "a$2"
ERROR: ParseError:
Error: identifier or parenthesized expression expected after $ in string
@ REPL[14]:1:4
"a$2"


julia> 
```
The error is correct but there is an extra blank line before the next prompt.

**Comment by JeffBezanson** [comment]
The output would also be much nicer if we can collapse
```
ERROR: ParseError:
Error: identifier or parenthesized expression expected after $ in string
```
into a single line, such as
```
ParseError: identifier or parenthesized expression expected after $ in string
```

**Comment by c42f** [comment]
> into a single line, such as

```
ParseError: identifier or parenthesized expression expected after $ in string
```

Yes. Though to remove the `ERROR:` prefix we would have to extend the function `Base.display_error` and that will be inconsistent with how we report other errors.  For example, the "double error" prefix occurs in basic things like

```
julia> 1÷0
ERROR: DivideError: integer division error
Stacktrace:
...
```

**Comment by c42f** [comment]
This was fixed some time ago.
