### ISSUE TITLE
Got ERROR: LoadError: MethodError: no method matching core_parser_hook(::String, ::String, ::Int64, ::Int64, ::Symbol) when using Visual Studio Code + Julia Language Support + Enable JuliaSyntax.jl at startup.jl

### ISSUE THREAD

**Issue by ysaereve** [JuliaLang/JuliaSyntax.jl#128]
Got ERROR: LoadError: MethodError: no method matching core_parser_hook(::String, ::String, ::Int64, ::Int64, ::Symbol) when 
- using Visual Studio Code () +
```
Version: 1.72.0
Commit: 64bbfbf67ada9953918d72e1df2f4d8e537d340e
Date: 2022-10-04T23:21:58.256Z (2 wks ago)
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.6.0
Sandboxed: No
``` 
- Julia Language Support +
```
v1.38.2
```
- Enable JuliaSyntax.jl at startup.jl +
- Julia: Start REPL

1. The output of `versioninfo()`
``` julia
julia> versioninfo()
Julia Version 1.8.1
Commit afb6c60d69a (2022-09-06 15:09 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin21.4.0)
  CPU: 16 × Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 4 on 8 virtual cores
Environment:
  JULIA_NUM_THREADS = 4
  JULIA_COPY_STACKS = 1
  JULIA_EDITOR = code
```
2. How you installed Julia
```
via juliaup
```
3. A minimal working example (MWE), also known as a minimum reproducible example

in ~/.julia/config/startup.jl:
``` julia
import JuliaSyntax
JuliaSyntax.enable_in_core!(true)
```

Error Messages:
``` julia
ERROR: LoadError: MethodError: no method matching core_parser_hook(::String, ::String, ::Int64, ::Int64, ::Symbol)
The applicable method may be too new: running in world age 32409, while current world is 32433.
Closest candidates are:
  core_parser_hook(::Any, ::Any, ::Any, ::Any, ::Any) at ~/.julia/packages/JuliaSyntax/Vnmrh/src/hooks.jl:104 (method too new to be called from this world context.)
  core_parser_hook(::Any, ::Any, ::Any, ::Any) at ~/.julia/packages/JuliaSyntax/Vnmrh/src/hooks.jl:118 (method too new to be called from this world context.)
Stacktrace:
 [1] _parse_string(text::String, filename::String, lineno::Int64, index::Int64, options::Symbol)
   @ Base.Meta ./meta.jl:198
 [2] #parseall#6
   @ ./meta.jl:284 [inlined]
 [3] include_string(mapexpr::typeof(identity), mod::Module, code::String, filename::String)
   @ Base ./loading.jl:1414
 [4] _include(mapexpr::Function, mod::Module, _path::String)
   @ Base ./loading.jl:1488
 [5] include(mod::Module, _path::String)
   @ Base ./Base.jl:419
 [6] exec_options(opts::Base.JLOptions)
   @ Base ./client.jl:303
 [7] _start()
   @ Base ./client.jl:522
in expression starting at ~/.vscode/extensions/julialang.language-julia-1.7.12/scripts/terminalserver/terminalserver.jl:1
```

**Comment by c42f** [comment]
Thanks for a nice bug report :heart:  I could reproduce in vscode (not immediately in the normal REPL though)

As a workaround, could you try the following in your startup.jl:

```julia
atreplinit() do repl
    @eval begin
        import JuliaSyntax
        JuliaSyntax.enable_in_core!(true)
    end
end
```

You could alternatively use a custom sysimage but that would require some extra fiddling around, as JuliaSyntax.jl and vscode have different ideas of how to set up the sysimage.

---

I think the following is a minimal reproducer without using vscode or startup.jl:

```julia
julia> function foo()
           eval(:(using JuliaSyntax; JuliaSyntax.enable_in_core!()))
           Meta.parse("blah")
       end
foo (generic function with 1 method)

julia> foo()
ERROR: MethodError: no method matching core_parser_hook(::String, ::String, ::Int64, ::Int64, ::Symbol)
The applicable method may be too new: running in world age 32444, while current world is 32445.
Closest candidates are:
  core_parser_hook(::Any, ::Any, ::Any, ::Any, ::Any) at ~/.julia/dev/JuliaSyntax/src/hooks.jl:106 (method too new to be called from this world context.)
  core_parser_hook(::Any, ::Any, ::Any, ::Any) at ~/.julia/dev/JuliaSyntax/src/hooks.jl:120 (method too new to be called from this world context.)
Stacktrace:
 [1] _parse_string(text::String, filename::String, lineno::Int64, index::Int64, options::Symbol)
   @ Base.Meta ./meta.jl:198
 [2] #parse#3
   @ ./meta.jl:235 [inlined]
 [3] parse(str::String; raise::Bool, depwarn::Bool)
   @ Base.Meta ./meta.jl:268
 [4] parse
   @ ./meta.jl:267 [inlined]
 [5] foo()
   @ Main ./REPL[1]:3
 [6] top-level scope
   @ REPL[2]:1

```

alternatively and for equivalent reasons the following fails

```julia
julia --startup-file=no -e 'using JuliaSyntax; JuliaSyntax.enable_in_core!()' -e 'println(1)'
```

So the problem is that the `eval` swaps out the value of `Core._parse` and `Meta.parse()` then fails to work until we return to top level execution. The `julia -e` reproducer basically does the same thing as `foo` in evaluating `Core.eval(Main, parse_input_line(arg))` for each `-e` argument option without returning to top level and grabbing a new world age.

Given all this, I don't see that this can be fixed except for documenting the workaround or documenting how to build a sysimage for using JuliaSyntax.jl with vscode.

**Comment by c42f** [comment]
For a custom sysimage you'll want the instructions here

https://www.julia-vscode.org/docs/dev/userguide/compilesysimage/#Creating-a-sysimage-for-the-active-environment

to include some of the JuliaSyntax tests as part of the precompile, as is done here: https://github.com/JuliaLang/JuliaSyntax.jl/blob/main/sysimage/precompile_exec.jl

then include the `enable_in_core!()` as part of startup.jl, just as you did previously (no `atreplinit()` workaround should be needed)

**Comment by ysaereve** [comment]
Thank you for the ❤️. I just tested the "atreplinit()" workaround. It works. 👍

**Comment by c42f** [comment]
I added some docs on this to the README in #132

**Comment by nstiurca** [comment]
This bug helped me, but for the record I ended up having to wrap with `invokelatest`, ie

    Base.invokelatest(JuliaSyntax.enable_in_core!, true)
