### ISSUE TITLE
'\ \\' returns ErrorVal

### ISSUE THREAD

**Issue by jakobnissen** [JuliaLang/JuliaSyntax.jl#138]
I think this should error instead of leaking the error value into the REPL
Flisp parser:
```
julia> '\ \\'
ERROR: syntax: invalid escape sequence
```

JuliaSyntax
```
julia> '\ \\'
✘

julia> typeof(ans)
JuliaSyntax.ErrorVal
```

**Comment by c42f** [comment]
Yes indeed. This is an almost-duplicate of #109, the fix will be the same.
