### ISSUE TITLE
Could you do Julia 2.0 (parsing) as an option?

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/JuliaSyntax.jl#141]
I recall at least three issues with parsing.

Since you opt into this package (even when it will be merged), could you have two ways, a) (meant to be) non-breaking, and b) proposed 2.0 Julia? Likely a) as default, not sure about slipping it in unnoticed... at least having both makes easy to see have breaking in practice this is, or how useful, with PkgEval.

1. This one would make:
https://github.com/JuliaLang/julia/issues/34999#issuecomment-625815233

>a whole order of magnitude faster. 

2. https://github.com/JuliaLang/julia/issues/47408#issuecomment-1300505825

3. And I believe |> has bad precedence.

**Comment by c42f** [comment]
Yes we already support multiple 1.x versions of Julia in this package. For example, `[a ;; b]` won't parse in Julia 1.6 but in 1.7 it is multidimensional array syntax:

```julia
 julia> JuliaSyntax.parse(Expr, "[1 ;; 2]", version=v"1.6")
ERROR: ParseError:
Error: multidimensional array syntax not supported in Julia version 1.6 < 1.7
@ line 1:1
[1 ;; 2]

julia> JuliaSyntax.parse(Expr, "[1 ;; 2]", version=v"1.7")
:([1;; 2])
```

Experimenting with Julia 2.0 syntax would also be a possibility in the future. Actually I believe that proposed future syntaxes *should* be available in 1.x on an experimental opt-in basis (maybe per-file or per-module). This allows for a bit more more flexibility in evolving syntax without fracturing the package ecoystem like the infamous python 2/3 split did.

I'll close this issue for now as we're not ready to start thinking about 2.0 syntax. Each potential syntax change for 2.0 would in any case need its own discussion on a repo where more people are paying attention (probably julialang/julia at this point).
