### ISSUE TITLE
Add milestones 

### ISSUE THREAD

**Issue by HiperMaximus** [JuliaLang/JuliaSyntax.jl#167]
It would be nice to add milestones or an issue to track the progress of the package, as imo this is one of the most important and exciting features for future Julia. Great work!

**Comment by timholy** [comment]
#134 is a good list of TODOs. Feel free to pitch in and help fix remaining items.

@c42f, OK to close this?

**Comment by c42f** [comment]
Yes, I think we can close this. At the present time, reviewing the JuliaSyntax issue list should give a sense of what is still to do, and if people want to know status/progress they can follow along with the PRs. Adding milestones probably won't help development at this stage so I'm afraid they're unlikely to be kept up to date.
