### ISSUE TITLE
Runtime Julia 1.0 support

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/JuliaSyntax.jl#180]
The package currently has Julia 1.6 as the min version. Is that essential? Or could it be made to work on Julia 1.0 as well?

I've been looking into adding this to the language server so that we can surface the fancy cool error messages, but that would only work if it runs on Julia 1.0 as well...

Eventually I hope to statically compile the language server, and at that point runtime support for old Julia versions would not be required anymore, but my sense is that that is not around the corner ;)

**Comment by c42f** [comment]
I think we can make this package work with 1.0.

The only thing which won't work is hooking JuliaSyntax into the Julia runtime - this requires Julia version 1.6 or above.
