### ISSUE TITLE
error when encountering format characters

### ISSUE THREAD

**Issue by simeonschaub** [JuliaLang/JuliaSyntax.jl#23]
Julia's parser seems to accept this:

```julia
julia> JuliaSyntax.parseall(JuliaSyntax.SyntaxNode, "\ufeffusing Test")
ERROR: ParseError:
Error: invalid syntax atom
@ line 1:1
using Test
Error: extra tokens after end of expression
@ line 1:2
using Test
```

There might be an argument to be made to just disallow this in Julia base.

Ref https://github.com/julia-vscode/CSTParser.jl/issues/333

**Comment by c42f** [comment]
Thanks. It seems like the decision was made to fix this in https://github.com/JuliaLang/Tokenize.jl/pull/197 rather than disallow it in Base. So I've ported that fix here as #26
