### ISSUE TITLE
Missing links in the README

### ISSUE THREAD

**Issue by waldyrious** [JuliaLang/JuliaSyntax.jl#312]
The README has a sentence that seems to be missing a couple links:

> Also watching the 2022 JuliaCon talk and reading this document is probably good for an overview.

The "2022 JuliaCon talk" bit should evidently link to the video at https://www.youtube.com/watch?v=CIiGng9Brrk, but I'm not sure what "this document" refers to. Maybe [this](https://julialang.github.io/JuliaSyntax.jl/dev/design/)?

**Comment by waldyrious** [comment]
Thanks for the update, @c42f! Out of curiosity, in relation to this bit:

> The intention is to extend this library over time to cover more of the Julia
compiler frontend.

...is there some sort of roadmap or tracking issue that one can follow? Or perhaps a more concrete description of what this increased coverage would entail?

**Comment by c42f** [comment]
> is there some sort of roadmap or tracking issue that one can follow

No :)

I wrote down the rough idea I have in my head at https://github.com/JuliaLang/JuliaSyntax.jl/issues/327
