### ISSUE TITLE
better error message for missing comma.

### ISSUE THREAD

**Issue by oscardssmith** [JuliaLang/JuliaSyntax.jl#313]
When missing a `,` in a list or function args, the error message currently says "expected `)`" when the real problem is the missing comma. Should the error message be updated to add that as a possibility? (examples where this comes up are `+(1, 2 3)` and `[1, 2 3]`)

**Comment by c42f** [comment]
We should be able to do better here  :+1:

We could probably emit "expected `,` or closing `)`" easily.

Distinguishing between possible recoveries and choosing the "best" one is a lot harder.
