### ISSUE TITLE
greedy=false parsing errors error

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/JuliaSyntax.jl#328]
```
julia> Meta.parse(",", 1, greedy=false)
┌ Error: JuliaSyntax parser failed — falling back to flisp!
│   exception =
│    BoundsError: attempt to access empty SubString{String} at index [0]
```

causing many issues on CI "doctest" worker, such as:
https://buildkite.com/julialang/julia-master/builds/25812#018947f5-cf43-4816-a3a7-d2248ed8294c/713-750

**Comment by c42f** [comment]
Fixed in the JuliaSyntax-0.4.6 release.
