### ISSUE TITLE
Docstrings on function call are strange

### ISSUE THREAD

**Issue by LilithHafner** [JuliaLang/JuliaSyntax.jl#335]
Somehow `"docstring" identifier()` adds the docstring to the identifier and discards the trailing parentheses. This should probably error.

```julia
julia> "abc" g()
g

julia> :("abc" g())
ERROR: ParseError:
# Error @ REPL[2]:1:9
:("abc" g())
#       └┘ ── Expected `)`
# Error @ REPL[2]:1:12
:("abc" g())
#          ╙ ── extra tokens after end of expression
Stacktrace:
 [1] top-level scope
   @ none:1

julia> g
ERROR: UndefVarError: `g` not defined

julia> @doc g
  abc
```

**Comment by pfitzseb** [comment]
This is intentional, afaict. You can attach docstrings to both functions and methods without those actually existing.

**Comment by KristofferC** [comment]
The docs say

```
 You can document an object after its definition by

  @doc "foo" function_to_doc
  @doc "bar" TypeToDoc
```

Could probably be changed to `before/after`.

**Comment by LilithHafner** [comment]
I missed that this adds a docstring to the method, not the function.
