### ISSUE TITLE
AutoPR?

### ISSUE THREAD

**Issue by ParadaCarleton** [JuliaLang/JuliaSyntax.jl#356]
Some tool like [AutoPR](https://github.com/irgolic/AutoPR/) that automatically makes PRs when asked could speed things up--most error message rewrites should be simple enough that an AI can do them before being reviewed by a person.

**Comment by c42f** [comment]
From a quick look at AutoPR I don't think I want to use it. I don't really want to commit that kind of autogenerated content to the repository.

In general I do think data driven models have a lot of potential for improving compiler error messages. If anyone wanted to do some serious research/prototyping in that direction, that would be amazing.
