### ISSUE TITLE
Syntax coloring for doctests

### ISSUE THREAD

**Issue by ShalokShalom** [JuliaLang/JuliaSyntax.jl#362]
Hi 👍🏻 

I know, I might be in the wrong repo, and I hope it reaches the right people anyway. 😺 

So, I just saw [this file](https://github.com/JuliaGraphics/QML.jl/blob/main/src/docs.jl) and all I am thinking about, is how I miss the syntax highlighting. 

Is it necessary, that we omit the syntax highlighting for doc tests?

**Comment by pfitzseb** [comment]
https://github.com/JuliaEditorSupport/atom-language-julia is the correct place for this issue. I'm not sure if it's possible to implement this though.

**Comment by c42f** [comment]
Syntax highlighting in the github.com interface? Or syntax highlighting in your editor?

In either case there's nothing we can do in JuliaSyntax.jl to help with this sorry :sweat_smile:
