### ISSUE TITLE
Error message could suggest comma instead of `)`

### ISSUE THREAD

**Issue by jakobnissen** [JuliaLang/JuliaSyntax.jl#363]
In the example:
```julia
julia> foo(a b)
ERROR: ParseError:
# Error @ REPL[2]:1:7
foo(a b)
#     ╙ ── Expected `)`
```
It would be better to suggest adding a `,` rather than a `)`. I don't know if this is feasible since it probably requires parsing ahead in front of the parser error to find the missing `)`

**Comment by KristofferC** [comment]
Dup of https://github.com/JuliaLang/JuliaSyntax.jl/issues/313
