### ISSUE TITLE
Better error for missing comma in arglist

### ISSUE THREAD

**Issue by jariji** [JuliaLang/JuliaSyntax.jl#411]
```jl
julia> f(foo, bar baz, quux)
ERROR: ParseError:
# Error @ 

f(foo, bar baz, quux)
#          └───────┘ ── Expected `)`
```

It says expected `)` but the problem is actually a missing `,` and adding a `)` wouldn't help. Maybe it could suggest several options instead of just one.

**Comment by Tortar** [comment]
duplicate of https://github.com/JuliaLang/julia/issues/52285

**Comment by Tortar** [comment]
Actually already fixed (see https://github.com/JuliaLang/julia/issues/52285) but we are still on an old version of JuliaSyntax in Julia :(
