### ISSUE TITLE
When using in REPL, `JuliaSyntax.jl` does not seem to work well with multiline parsing?

### ISSUE THREAD

**Issue by singularitti** [JuliaLang/JuliaSyntax.jl#42]
When I want to type

```julia
map(1:10) do x
    2x
end
```

after I type `map(1:10) do x` and hit return, I got

```julia
julia> map(1:10) do
ERROR: ParseError:
Error: premature end of input
@ REPL[11]:2:1
map(1:10) do
Error: premature end of input
@ REPL[11]:2:1
map(1:10) do
Error: Expected `end` but got unexpected tokens
@ REPL[11]:2:1
map(1:10) do
```

Or if I want to type

```julia
 w = u +
     v +
     1
```

I got

```julia
julia> w = u +
ERROR: ParseError:
Error: premature end of input
@ REPL[14]:2:1
w = u +
```

But I can do them with copy-paste:

<img width="153" alt="image" src="https://user-images.githubusercontent.com/25192197/184258129-75b6ec6c-a101-4827-805d-a669d7121844.png">

Can we make the REPL-mode tolerate multiline code a little bit more?

**Comment by c42f** [comment]
Yes this is a bug, thanks for opening an issue!

What we need to do is detect "incomplete" expressions and emit `Expr(:incomplete)` for these to make this work.

In the meantime, you can use the REPL's `ALT+Return` keybinding to enter a newline without going through the parser (this is what keeps me sane :sweat_smile: )

**Comment by singularitti** [comment]
Hi @c42f, I just tried `Alt+Return` (on macOS is it probably `Option+Return`?) But it does not seem to work. Is it a different keybinding on Macs? I have tried `Control+Return` & `Command+Return` though.

**Comment by c42f** [comment]
I'm not sure I don't use macOS.  It might be a setting on your terminal emulator https://apple.stackexchange.com/questions/1391/equivalent-to-alt-in-terminal ?

**Comment by singularitti** [comment]
Oh, it works. Maybe because I was using iTerm? I don't know.
