### ISSUE TITLE
Failing unit tests on Julia nightly

### ISSUE THREAD

**Issue by JamieMair** [JuliaLang/JuliaSyntax.jl#424]
The CI in MuJoCo.jl is failing due to an error in this package. I am opening a bug report as requested in the error. You can find [the logs of the error here](https://github.com/JamieMair/MuJoCo.jl/actions/runs/8144077366/job/22257384395).

**Comment by LilithHafner** [comment]
The log of the error is missing. This is no longer actionable, sorry.
