### ISSUE TITLE
Generator syntax incorrectly parses extra code vs Julia 1.6 parser

### ISSUE THREAD

**Issue by mkitti** [JuliaLang/JuliaSyntax.jl#428]
Julia 1.10.2:

```julia
julia> (x for x in 1:5 6)
6
```

Julia 1.6
```julia
julia> (x for x in 1:5 5)
ERROR: syntax: expected ")"
```

I originally discovered this error in 1.10.2 by trying to run the following and thinking that Julia may have gotten too smart.

```julia
julia> (x for x in in 1:5)
1:5
```

**Comment by pfitzseb** [comment]
Dup of https://github.com/JuliaLang/JuliaSyntax.jl/issues/407.
