### ISSUE TITLE
improve error message for `new` missing type parameters.

### ISSUE THREAD

**Issue by oscardssmith** [JuliaLang/JuliaSyntax.jl#431]
Currently the following code
```
struct A{T}
    t::T
    function A(t)
        new(t)
    end
end
 ```
 produces the syntax error
 ```
ERROR: syntax: too few type parameters specified in "new{...}" around REPL[3]:1
Stacktrace:
 [1] top-level scope
   @ REPL[3]:1
```
This isn't a *bad* error message; it correctly identifies `new` missing type parameters, but it's missing the nice JuliaSyntax highlighting, and doesn't say how many parameters were expected (not needed in this example, but for types with lots of params, it would be useful).

**Comment by MasonProtter** [comment]
I'm pretty sure this error is emitted from lowering, not from parsing so that's why it's so much less informative. Hopefully once lowering is in the julia side this can be fixed.

**Comment by c42f** [comment]
Yep, this can't be fixed in parsing. I'd move it to JuliaLowering.jl but it seems I'll need to move that to the JuliaLang org first.

**Comment by c42f** [comment]
I'd forgotten about this issue, but it's now fixed in JuliaLowering.jl!  From the tests, we now get:

```julia
LoweringError:
struct X{S,T}
    X() = new{A}()
#         └────┘ ── too few type parameters specified in `new{...}`
end
```

See also the JuliaLowering test cases for related errors:

https://github.com/c42f/JuliaLowering.jl/blob/760de66c8a9d38c9b25c5279d35d2f7903578512/test/typedefs_ir.jl#L1077-L1086

**Comment by c42f** [comment]
Maybe one day we can refer to multiple source ranges (https://github.com/c42f/JuliaLowering.jl/issues/8) and have something even better like

```julia
LoweringError:
struct X{S,T}
#      └─1──┘
    X() = new{A}()
#         └┈2┈┈┘ ── Too few type parameters specified in `new{...}`
end

# The number of parameters in the [call to `new{...}`](┈2┈)  must match the number
# parameters in the [type signature](─1─). Try adding the missing parameters.
# `new()` may also be called without type arguments when they can be inferred
# from the constructor signature.
```
