### ISSUE TITLE
Tests fail on Julia 1.10 and 1.11-rc

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/JuliaSyntax.jl#444]
I wanted to include running JuliaSyntax.jl tests into the VS Code extension release pipeline (https://github.com/julia-vscode/julia-vscode/pull/3625), but it turns out that tests fail on both Julia 1.10 and 1.11-rc. And it turns out that CI here isn't run for anything newer than 1.8. I think it would generally be good if this package here ran CI on minimally all released versions regularly, plus beta or release candidates.

**Comment by LilithHafner** [comment]
CI runs on pretty much all of those, the problem is primarily that it's failing.
