### ISSUE TITLE
Incorrect parsing of array literal with newline before comma

### ISSUE THREAD

**Issue by oscardssmith** [JuliaLang/JuliaSyntax.jl#59]
On Julia master,
```
[ []
, [] ]
```
parses correctly as a `Vector{Vector{Any}}`, but with JuliaSyntax, we get the `ParseError`
```
Error: Expected `]`
@ REPL[11]:2:3
[ []
  ,[] ]
```
This is a fairly major bug since this prevents loading CpuId which depends on this syntax.

**Comment by c42f** [comment]
> fairly major bug

Definitely a problematic bug! Whether it's a more major one than the other known bugs I don't know :sweat_smile:
